[package]
name = "crypto_rs"
version = "0.1.0"
edition = "2021"
authors = ["sandmannmax <mail@mxsandmann.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint-dig = "0.8.2"
num-traits = "0.2.15"
